package com.tiancaijiazu.app.differentiateenum;

/**
 * Created by Administrator on 2019/5/18/018.
 */

public enum DifferentiateEnum {
    //刷新token
    REFRESH,
    //注册
    REGISTER,
    //短信验证码
    CODE,
    //密码登录
    MIMALOFIN,
    //短信登录
    CODELOGIN,
    //商品规格
    SPECIFICATIONOFGOODS,
    //发布文章
    PUBLISHARTICLE,
    //成长日记列表
    GROUPLIST,
    //修改日记可见范围
    MODIFIER,
    //用户发布的成长日记列表
    DIARYDEITL,
    //文章列表
    ARTICLELISTS,
    //文章内容
    ARTICLEDATAS,
    //点赞
    GIVEALIKE,
    //评论
    COMMENT,
    //点赞列表
    LIKELISTS,
    //一級评论列表
    ONECOMMENTLISTS,
    //二级评论列表
    TWOCOMMENTLISTS,
    //删除评论
    DELETECOMMENT,
    //关注
    CONCERN,
    //收藏
    COLLECT,
    //用户中心
    USERCENTER,
    //Ta的关注
    ITATTENTION,
    //Ta的粉丝
    ITFANS,
    //话题列表
    TOPICLISTS,
    //话题内容页
    TOPICDATAS,
    //搜索话题
    SOUTOPICLIST,
    //获取课程分类列表
    PARENTID,
    //获取课程详情
    COURSEID,
    //微信登录
    WXLOGIN,
    //微信绑定手机号
    WXBINDING,
    //添加到购物车
    ADDSHOPCAR,
    //修改购物车中的商品
    UPDATESHOPCAT,
    //删除购物车中的商品
    REMOVESHOPCAR,
    //购物车列表
    SHOPPINGLIST,
    //商品列表
    SHANGPINLIST,
    //添加地址
    ADDDIZHI,
    //地址列表
    SITELIST,
    //删除地址
    DELESITE,
    //设置默认地址
    TACITLYSITE,
    //修改地址
    EDITADDRESS,
    //订单列表
    ORDERLIST,
    //提交订单
    ORDERFORM,
    //订单详情
    ORDERDETAIL,
    //发起微信支付
    PAYBEAN,
    //发起支付宝支付
    ALIPAY,
    //学院课程不带商品购买
    COURSETOBUY,
    //学院课程带赠品购买
    COURSETOBUYCOMM,
    //学院调起支付宝支付
    ALIPAYCURSE,
    //学院调起微信支付
    PAYBEANCURSE,
    //个人信息
    USERINFO,
    //更改昵称
    CHANGENICHENG,
    //更改个性签名
    CHANGEGEQIAN,
    //修改头像
    XIV,
    //修改性别
    UPSEX,
    //修改城市
    UPADDRESS,
    //已购课程
    ABC,
    //获取课程列表
    COURSELIST,
    //商城类目列表
    SHOPBEAN,
    //宝宝信息列表
    BABYMESSAGELIST,
    //添加宝宝信息
    ADDBABY,
    //删除宝宝卡
    DELETEBABY,
    //修改宝宝卡信息
    UPBABY,
    //设置默认宝宝卡
    SETBABY,
    //设置首页轮播图
    HOMEBANNAR,
    //首页短视频
    SHORTVIDEO,
    //首页广告位
    ADPOSITION,
    //歌单列表
    SONGLIST,
    //歌曲详情
    SONG,
    //获取歌单详情
    DIANSONG,
    //首页早安音乐
    SONGMORN,
    //首页晚安音乐
    SONGNIGHT,
    //早安 晚安 电台页面
    SONGMORNS,
    //早安 晚安 电台列表
    SONGMUSIC,
    //商城轮播图
    SHOPBANNAR,
    //首页社区
    HOMEBSS,
    //测评问卷列表
    EVALUATIONLIST,
    //测评对应月龄题目
    REVIEWTHETOPIC,
    //获得我的收藏列表
    MYCOLLECTLIST,
    //获得我的发帖文章
    MYRELEASEDLIST,
    //提交测评
    SUBMITAPPRAISAL,
    //宝宝测评结果
    EVALUATIONRESULTS,
    //宝宝对应测评列表
    REVIEWEDLIST,
    //线下园所列表
    CLASSGARDENLIST,
    //园所详情
    GARDENDETAILSBY,
    //提交线下加盟
    TOJOIN,
    //提交线下课堂预约申请
    TOJOINBABY,
    //早教课程列表
    EARLYCOURSELIST,
    //早教课程详情
    EARLYCOURSE,
    //获取优惠券列表
    COUPONLIST,
    //领取家庭早教课程专享优惠券
    GETCOUPONONLYATHOME,
    //会员级别列表
    VIPLIST,
    //创建会员升级订单
    VIPORDER,
    //vip微信支付
    VIPWXPAY,
    //vip支付宝支付
    VIPALIPAY,
    //商城广告_首页优选爆品
    MALLADONE,
    //商城广告_首页自有品牌推荐
    MALLADTWO,
    //商城广告_自有品牌_好物推荐
    MALLADTHREE,
    //商城广告_自有品牌_顶部Banner
    MALLADSIX,
    //商城广告_母婴服饰_好物推荐
    MALLADFOUR,
    //商城广告_儿童车床_好物推荐
    MALLADFIVE,
    //商城广告_母婴服饰_顶部Banner
    MALLADSEVEN,
    //商城广告_儿童车床_顶部Banner
    MALLADEIGHT,
    //学院广告_首页短视频体验课
    STUDYADONE,
    //学院广告_首页短音频体验课
    STUDYADTWO,
    //学院广告_早教学院新课速递
    STUDYADTHREE,
    //学院广告_早教学院好课推荐
    STUDYADFOUR,
    //学院广告_智慧学院精品推荐
    STUDYADFIVE,
    //商城广告_首页首屏小Banner
    MALLADNINE,
    //精选话题列表，用于社区首页顶部导航
    COMMTOPICSWITCHER,
    //获取已关注作者的文章列表
    ARTICLELISTFOLLOW,
    //商城广告_详情页_为你推荐
    MALLADTEN,
    //商城广告_详情页_看了又看
    MALLADELEVEN,
    //发布商品评价
    POSTCOMMENT,
    //获取商品评价列表
    COMMENTLIST,
    //获取当前推送的课程详情
    FORMALCURRICULUM,
    //获取家庭早教学习卡列表
    CARDTYPEBEAN,
    //学卡微信支付
    STUDYCARDWEIXIN,
    //学卡支付宝支付
    STUDYCARDZHIFUBAO,
    //创建家庭早教学习卡订单
    STUDYCARDORDERCREATE,
    //获取某使用场景下的有效优惠券数量
    VALIDCOUPONS,
    //用户当前卡类型
    USERCARDTYPE,
    //个人中心用户提交反馈
    MEMBERFEEDBACK,
    //社区文章、课程记录内容举报
    ARYICLEREPORT,
    //提交课后反馈，获取推荐游戏
    SUBMIT,
    //取消商城订单
    ORDERCANNEL,
    //获取APP首页每日小游戏列表
    GAMEHOMEPAGE,
    //获取短视频分类列表
    RESPECTIVELY,
    //按分类ID获取短视频列表
    MINVIDEO,
    //获取用户的收入汇总信息
    INCOME,
    //视频，领取试听卡页面专用
    AUDITION,
    //获取用户的收入明细列表
    DETAIL,
    //获取我的团队成员列表
    TEAM,
    //检查app最新版本
    APPCHECKVERSION,
    //H5地址列表，供APP调起H5模块专用
    BRING,
    //获取包含用户二维码的图片
    QRCODE,
    //保存、修改银行卡信息
    BANKCARDMODIFY,
    //获取用户的银行卡信息bankcard_info
    BANKCARDINFO,
    //WEB收藏、取消收藏
    WEBCOLLECT,
    //WEB验证文章是否已收藏
    WEBISCOLLECT,
    //获取用户已收藏的百科文章列表
    WEBCOLLECTLIST,
    //删除社区文章
    DELEARTICEL,
    //当前正在上课的总人数
    PEOSUM,
    //当前领取试听卡的用户列表
    GETCARDS,
    //收藏、取消收藏短视频
    SHORTCOLLECT,
    //检查是否已收藏短视频
    SHORTISCOLLECT,
    //用户收藏的短视频列表
    SHORTCOLLECTLIST,
    //按宝宝生日获取当前问卷ID
    GETSUBID,
    //免费获取“推广大使”身份标识
    UPGRADE,
    //获取用户的可提现余额
    AMOUNT,
    //提现申请
    APPLY,
    //提现记录明细
    CASHDETAIL,
    //提现记录列表
    DetailList,
}
